language: java

jdk:
    - oraclejdk8

services:
    - mysql

before_install: 
    - mysql -uroot -e "grant all on test.* to test-user@localhost identified by 'test-password'"
    - mysql -uroot -e "drop database if exists test"
    - mysql -uroot -e "create database test"
